#pragma once

#include "CoreMinimal.h"
#include "CSGpuDebugDraw.h"
#include "GameFramework/Actor.h"
#include "CSPointBrushActor.generated.h"

class ACSPointBrushActor;
class UCSDisplayComponent;
class UCSGpuInstancedMeshComponent;
class UMaterialInterface;
class UStaticMesh;

DECLARE_MULTICAST_DELEGATE_OneParam(FCSPointBrushEditorRequest, ACSPointBrushActor*);

/** One painted sample: where the brush hit, and the surface normal there. */
USTRUCT(BlueprintType)
struct COMPUTESHADERGENERATOR_API FCSBrushPoint
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush")
	FVector Position = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush")
	FVector Normal = FVector::UpVector;
};

/**
 * An actor you paint points onto, which keeps the result as GPU buffers a compute pass can read
 * without any round trip.
 *
 * PointBuffers is where painted points live: float4 positions, float4 normals, and a 2-uint
 * counter whose [0] is the live point count. A consumer registers those pooled buffers into its
 * own graph (RegisterExternalBuffer) and dispatches indirectly off the counter, so neither the
 * points nor the count ever come back to the CPU.
 *
 * The brush writes that buffer straight from a compute pass that samples the scene depth buffer
 * (FCSDepthBrushSampleService), which is what keeps a sample on a surface the viewport can
 * actually see. Nothing is read back, so PaintedPoints is NOT filled by painting: it only holds
 * what was authored or loaded before, and painted points do not survive a level reload. The
 * InstanceMesh display path reads PaintedPoints and therefore only shows that older set; the
 * arrow path reads PointBuffers and shows everything.
 *
 * Lifetime: the pooled refs held here are the only owners of that GPU memory. They are dropped on
 * the render thread when the buffer is rebuilt or cleared, when play ends, when the actor is
 * deleted, and when the actor is garbage-collected — which covers closing the level and shutting
 * down the engine. Nothing outside this actor has to remember to free them.
 *
 * Display picks one of two paths from InstanceMesh:
 *   set   — UCSGpuInstancedMeshComponent draws one instance of that mesh per sample, +Z aligned to
 *           the sample normal. Geometry is stored once and the cluster/instance cull and LOD
 *           selection run on the GPU, so a dense paint costs one indirect draw per LOD.
 *   empty — the original GPU debug arrows (UCSDisplayComponent::ShowPointArrows), generated by a
 *           compute pass straight from PointBuffers.
 * Only one of the two components ever holds content; switching clears the other.
 */
UCLASS(Blueprintable)
class COMPUTESHADERGENERATOR_API ACSPointBrushActor : public AActor
{
	GENERATED_BODY()

public:
	ACSPointBrushActor();

	/** Raised by StartPointBrush(); the editor module answers it by activating the brush EdMode. */
	static FCSPointBrushEditorRequest OnPointBrushEditorRequest;

	// -------------------------------------------------------------------------
	// Brush Settings
	// -------------------------------------------------------------------------

	/** Brush sphere radius in cm. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush")
	float BrushRadius = 500.0f;

	/** Candidate samples scattered per mouse-move while a stroke is active. The whole batch is one
	 *  compute thread group, which is what caps it. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush", meta = (ClampMin = "1", ClampMax = "256"))
	int32 SamplesPerMouseMove = 16;

	/** Minimum distance in cm between two points, checked against the batch and everything already
	 *  in the GPU buffer. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush")
	float MinSpacing = 100.0f;

	/** Sphere-sweep radius for the cursor trace that positions the brush sphere. 0 uses a line
	 *  trace. Sampling itself no longer traces. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush")
	float TraceRadius = 0.0f;

	/** Leave the brush mode after each committed stroke. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush")
	bool bExitAfterCommit = false;

	/** Restrict painting to PaintBoundsExtent around the actor. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush")
	bool bUsePaintBounds = false;

	/** Half-size of the paint box, used when bUsePaintBounds is set. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush", meta = (EditCondition = "bUsePaintBounds"))
	FVector PaintBoundsExtent = FVector(5000.0);

	/** Hard cap on stored points; also the allocated GPU capacity, which the brush appends into and
	 *  cannot grow. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush", meta = (ClampMin = "1"))
	int32 MaxPointCount = 65536;

	// -------------------------------------------------------------------------
	// GPU Display
	//
	// 每个绘制点显示为一个实例：网格由 InstanceMesh 决定，为空时用内置的箭头（沿 +Z），
	// 实例的 +Z 对齐该点法线。走 UCSGpuInstancedMeshComponent —— 一份几何 + 每实例
	// transform，逐帧的簇/实例剔除与 LOD 选择都在 GPU 上做。
	// -------------------------------------------------------------------------

	/** 每个点实例化的网格。**为空时回退到原来的 GPU 箭头显示**（ArrowLength / PointColor 生效）。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Display")
	TObjectPtr<UStaticMesh> InstanceMesh;

	/** 实例材质，仅 InstanceMesh 非空时使用。为空时用引擎默认表面材质。
	 *  自定义材质必须勾选 "Used with Instanced Static Meshes"。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Display")
	TObjectPtr<UMaterialInterface> InstanceMaterial;

	/** InstanceMesh 的统一缩放。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Display", meta = (ClampMin = "0.001"))
	float InstanceScale = 1.0f;

	/** 箭头颜色（写进顶点色）。仅 InstanceMesh 为空时生效。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Display")
	FLinearColor PointColor = FLinearColor(1.0f, 0.85f, 0.1f);

	/** 箭头总长（沿法线）。仅 InstanceMesh 为空时生效。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Display", meta = (ClampMin = "0.01"))
	float ArrowLength = 50.0f;

	/** Cap on drawn points. 0 draws every point in the buffer. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Debug Draw", meta = (ClampMin = "0"))
	int32 MaxPointsToDraw = 0;

	/** Rebuild the GPU buffer from the saved points when the level loads this actor. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Debug Draw")
	bool bRebuildBufferOnLoad = true;

	// -------------------------------------------------------------------------
	// Painted Data
	// -------------------------------------------------------------------------

	/** Points authored outside the brush; saves with the level. The brush no longer appends here —
	 *  its samples only ever exist in PointBuffers. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "CS Point Brush|Data")
	TArray<FCSBrushPoint> PaintedPoints;

	// -------------------------------------------------------------------------
	// Public API
	// -------------------------------------------------------------------------

	/** Opens the editor-side point brush tool for this actor. */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "CS Point Brush", meta = (DevelopmentOnly))
	void StartPointBrush();

	/** Appends points (clamped to MaxPointCount), rebuilds the GPU buffer, and refreshes the draw.
	 *  Returns how many were actually added. */
	UFUNCTION(BlueprintCallable, Category = "CS Point Brush")
	int32 AppendBrushPoints(const TArray<FCSBrushPoint>& NewPoints);

	/** Drops every painted point along with the GPU buffer and the debug draw. */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "CS Point Brush")
	void ClearBrushPoints();

	/** Allocates a MaxPointCount-sized GPU buffer and seeds it with PaintedPoints. Blocks on the
	 *  render thread. Anything the brush had appended is dropped — the CPU has no copy of it. */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "CS Point Brush")
	bool RebuildPointBuffer();

	/** The buffer the depth brush appends into, allocated on demand. Returns false if it could not
	 *  be created, in which case a stroke has nowhere to write. */
	bool EnsureGpuPointBuffer();

	/** Records that a stroke update asked the GPU for up to CandidateCount more points inside the
	 *  given brush sphere. Both are upper bounds — the GPU count is never read back — and they are
	 *  what sizes the arrow geometry and the draw bounds. */
	void NotifyGpuPointsRequested(int32 CandidateCount, const FVector& InBrushCentre, float InBrushRadius);

	/** Rebuilds the instanced display from PaintedPoints using the current display settings. */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "CS Point Brush")
	void RefreshDebugDraw();

	/** The component the painted points are drawn with; its Culling category holds the GPU
	 *  frustum / distance / LOD knobs. */
	UFUNCTION(BlueprintPure, Category = "CS Point Brush")
	UCSGpuInstancedMeshComponent* GetPointInstanceComponent() const { return PointInstanceComponent; }

	/** Releases the GPU buffer and clears the debug draw. PaintedPoints is untouched. */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "CS Point Brush")
	void ReleasePointBuffer();

	/** Only the authored/loaded points. What the brush painted lives on the GPU and is not counted. */
	UFUNCTION(BlueprintPure, Category = "CS Point Brush")
	int32 GetBrushPointCount() const { return PaintedPoints.Num(); }

	UFUNCTION(BlueprintPure, Category = "CS Point Brush")
	bool HasPointBuffer() const { return PointBuffers.IsValid(); }

	/** The GPU-resident painted points. Register these into your own graph; do not read them back. */
	const FCSGpuDebugPooledSource& GetPointBuffers() const { return PointBuffers; }

	/** Tests a candidate placement against the optional paint bounds. */
	bool IsBrushPointAllowed(const FVector& WorldPosition) const;

	/** Paint box in world space; only meaningful when bUsePaintBounds is set. */
	FBox GetPaintBoundsWorldBox() const;

	//~ AActor interface
	virtual void PostRegisterAllComponents() override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;
	virtual void Destroyed() override;
	virtual void BeginDestroy() override;
#if WITH_EDITOR
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent) override;
#endif

private:
	/** Bounding box of PaintedPoints, or an empty box when there are none. */
	FBox ComputePaintedPointBounds() const;

	/** Arrow geometry has to be allocated for a point count, and the real one lives on the GPU.
	 *  This is the CPU-side upper bound: what was seeded plus every candidate the brush asked for. */
	int32 GetDisplayPointCount() const;

	/** Used when InstanceMesh is set; its Culling category holds the GPU cull / LOD knobs. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "CS Point Brush|Display", meta = (AllowPrivateAccess = "true"))
	TObjectPtr<UCSGpuInstancedMeshComponent> PointInstanceComponent;

	/** Used when InstanceMesh is empty: the original compute-generated arrows. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "CS Point Brush|Display", meta = (AllowPrivateAccess = "true"))
	TObjectPtr<UCSDisplayComponent> PointArrowComponent;

	/** Where painted points live. Not a UPROPERTY — it holds render resources. */
	FCSGpuDebugPooledSource PointBuffers;

	/** Upper bound on PointBuffers' live count; see GetDisplayPointCount. */
	int32 GpuPointCountUpperBound = 0;
};
