#pragma once

#include "CoreMinimal.h"
#include "CSGpuDebugDraw.h"
#include "GameFramework/Actor.h"
#include "CSPointBrushActor.generated.h"

class ACSPointBrushActor;
class UCSDisplayComponent;

DECLARE_MULTICAST_DELEGATE_OneParam(FCSPointBrushEditorRequest, ACSPointBrushActor*);

/** One painted sample: where the brush hit, and the surface normal there. */
USTRUCT(BlueprintType)
struct COMPUTESHADERGENERATOR_API FCSBrushPoint
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush")
	FVector Position = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush")
	FVector Normal = FVector::UpVector;
};

/**
 * An actor you paint points onto, which keeps the result as GPU buffers a compute pass can read
 * without any round trip.
 *
 * Two representations, one owner:
 *   - PaintedPoints is the CPU truth. It is a UPROPERTY, so it saves with the level and survives
 *     reload; it is also what the editor brush appends to.
 *   - PointBuffers is the GPU mirror rebuilt from it: float4 positions, float4 normals, and a
 *     2-uint counter whose [0] is the live point count. A consumer registers those pooled buffers
 *     into its own graph (RegisterExternalBuffer) and dispatches indirectly off the counter, so
 *     neither the points nor the count ever come back to the CPU.
 *
 * Lifetime: the pooled refs held here are the only owners of that GPU memory. They are dropped on
 * the render thread when the buffer is rebuilt or cleared, when play ends, when the actor is
 * deleted, and when the actor is garbage-collected — which covers closing the level and shutting
 * down the engine. Nothing outside this actor has to remember to free them.
 *
 * The painted result is displayed through the shared GPU debug draw: one point per sample plus an
 * optional normal line, generated by a compute pass straight from these buffers.
 */
UCLASS(Blueprintable)
class COMPUTESHADERGENERATOR_API ACSPointBrushActor : public AActor
{
	GENERATED_BODY()

public:
	ACSPointBrushActor();

	/** Raised by StartPointBrush(); the editor module answers it by activating the brush EdMode. */
	static FCSPointBrushEditorRequest OnPointBrushEditorRequest;

	// -------------------------------------------------------------------------
	// Brush Settings
	// -------------------------------------------------------------------------

	/** Brush sphere radius in cm. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush")
	float BrushRadius = 500.0f;

	/** Candidate samples traced per mouse-move while a stroke is active. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush")
	int32 SamplesPerMouseMove = 16;

	/** Minimum distance in cm between two points, checked against the stroke and the committed set. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush")
	float MinSpacing = 100.0f;

	/** Sphere-sweep radius for the placement trace. 0 uses a line trace. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush")
	float TraceRadius = 0.0f;

	/** Leave the brush mode after each committed stroke. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush")
	bool bExitAfterCommit = false;

	/** Restrict painting to PaintBoundsExtent around the actor. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush")
	bool bUsePaintBounds = false;

	/** Half-size of the paint box, used when bUsePaintBounds is set. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush", meta = (EditCondition = "bUsePaintBounds"))
	FVector PaintBoundsExtent = FVector(5000.0);

	/** Hard cap on stored points; also the allocated GPU capacity. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Brush", meta = (ClampMin = "1"))
	int32 MaxPointCount = 65536;

	// -------------------------------------------------------------------------
	// Stroke Preview (drag-time only, CPU-side)
	// -------------------------------------------------------------------------

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Preview")
	float PreviewPointSize = 8.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Preview")
	float PreviewLifetime = 0.1f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Preview")
	FColor PreviewPointColor = FColor::Cyan;

	// -------------------------------------------------------------------------
	// GPU Debug Display
	// -------------------------------------------------------------------------

	/** Colour of the per-point dot. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Debug Draw")
	FLinearColor PointColor = FLinearColor(1.0f, 0.85f, 0.1f);

	/** Colour of the per-point normal line. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Debug Draw")
	FLinearColor NormalColor = FLinearColor(0.15f, 0.5f, 1.0f);

	/** Draw the normal line. When false the line collapses to nothing and only dots remain. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Debug Draw")
	bool bDrawNormals = true;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Debug Draw", meta = (EditCondition = "bDrawNormals"))
	float NormalLength = 50.0f;

	/** Cap on drawn points. 0 draws every point in the buffer. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Debug Draw", meta = (ClampMin = "0"))
	int32 MaxPointsToDraw = 0;

	/** Rebuild the GPU buffer from the saved points when the level loads this actor. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "CS Point Brush|Debug Draw")
	bool bRebuildBufferOnLoad = true;

	// -------------------------------------------------------------------------
	// Painted Data
	// -------------------------------------------------------------------------

	/** CPU truth for the painted set; saves with the level. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "CS Point Brush|Data")
	TArray<FCSBrushPoint> PaintedPoints;

	// -------------------------------------------------------------------------
	// Public API
	// -------------------------------------------------------------------------

	/** Opens the editor-side point brush tool for this actor. */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "CS Point Brush", meta = (DevelopmentOnly))
	void StartPointBrush();

	/** Appends points (clamped to MaxPointCount), rebuilds the GPU buffer, and refreshes the draw.
	 *  Returns how many were actually added. */
	UFUNCTION(BlueprintCallable, Category = "CS Point Brush")
	int32 AppendBrushPoints(const TArray<FCSBrushPoint>& NewPoints);

	/** Drops every painted point along with the GPU buffer and the debug draw. */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "CS Point Brush")
	void ClearBrushPoints();

	/** Re-uploads PaintedPoints into a freshly allocated GPU buffer. Blocks on the render thread. */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "CS Point Brush")
	bool RebuildPointBuffer();

	/** Re-submits the current GPU buffer to the debug component using the current draw settings. */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "CS Point Brush")
	void RefreshDebugDraw();

	/** Releases the GPU buffer and clears the debug draw. PaintedPoints is untouched. */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "CS Point Brush")
	void ReleasePointBuffer();

	UFUNCTION(BlueprintPure, Category = "CS Point Brush")
	int32 GetBrushPointCount() const { return PaintedPoints.Num(); }

	UFUNCTION(BlueprintPure, Category = "CS Point Brush")
	bool HasPointBuffer() const { return PointBuffers.IsValid(); }

	/** The GPU-resident painted points. Register these into your own graph; do not read them back. */
	const FCSGpuDebugPooledSource& GetPointBuffers() const { return PointBuffers; }

	/** Tests a candidate placement against the optional paint bounds. */
	bool IsBrushPointAllowed(const FVector& WorldPosition) const;

	/** Paint box in world space; only meaningful when bUsePaintBounds is set. */
	FBox GetPaintBoundsWorldBox() const;

	//~ AActor interface
	virtual void PostRegisterAllComponents() override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;
	virtual void Destroyed() override;
	virtual void BeginDestroy() override;
#if WITH_EDITOR
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent) override;
#endif

private:
	/** Bounding box of PaintedPoints, or an empty box when there are none. */
	FBox ComputePaintedPointBounds() const;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "CS Point Brush|Debug Draw", meta = (AllowPrivateAccess = "true"))
	TObjectPtr<UCSDisplayComponent> PointDebugComponent;

	/** GPU mirror of PaintedPoints. Not a UPROPERTY — it holds render resources. */
	FCSGpuDebugPooledSource PointBuffers;
};
